ecosystem:
  main_project: drools
  projects:
  - name: drools
    regexs:
    - drools.*
git:
  branches:
  - name: jenkins-test
    main_branch: true

seed:
  config_file:
    git:
      repository: drools
      author:
        name: tkobayas
        credentials_id: tkobayas
      branch: jenkins-test
    path: .ci/jenkins/config/branch.yaml
  jenkinsfile: dsl/seed/jenkinsfiles/Jenkinsfile.test
jenkins:
  agent:
    docker:
      builder:
        image: docker.io/apache/incubator-kie-kogito-ci-build:main-latest
        args: --privileged --group-add docker
