name: Publish webpage

on:
  push:
    branches:
      - drools-docs-test01
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Java and Maven Setup
        uses: apache/incubator-kie-kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: [17]
          maven-version: ['3.9.6']
          allow-snapshots: true
      - name: Build with Maven
        run: mvn -B clean install --file drools-docs/pom.xml
    
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: drools-docs/target/drools-docs-999-SNAPSHOT
